name: pkglog
description: A package providing logging functions to libraries.
version: 0.2.0
repository: https://github.com/vi-k/pkglog

topics:
  - debugging
  - logging

environment:
  sdk: ^3.2.0

dependencies:
  meta: ^1.17.0

dev_dependencies:
  leak_tracker: ^10.0.8
  lints: ^5.1.1
  test: ^1.24.0
  vm_service: ^15.0.2
