name: pkglog
description: Logger for package logging.
version: 0.1.0
repository: https://github.com/vi-k/pkglog

environment:
  sdk: ^3.1.0

dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
