name: pkglog
description: A fundamentally minimalistic package providing logging functions to libraries.
version: 0.1.2
repository: https://github.com/vi-k/pkglog

topics:
  - debugging
  - logging

environment:
  sdk: ^3.2.0

# dependencies:

dev_dependencies:
  leak_tracker: ^10.0.8
  lints: ^5.1.1
  test: ^1.24.0
  vm_service: ^15.0.2
