name: loggo
description: A starting point for Dart libraries or applications.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
