name: pkglog
description: A fundamentally minimalistic package providing logging functions to libraries.
version: 0.1.2
repository: https://github.com/vi-k/pkglog

topics:
  - debugging
  - logging

environment:
  sdk: ^3.1.0

dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
