name: pkglog_example
description: An example for pkglog.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  ansi_escape_codes: ^2.1.0
  pkglog:
    path: ../../

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
